### PR TITLE
Update FangOff.py

### PR DESCRIPTION
**Pull request by MylesBock**
i saw this tweeted and said `i'm bored and this is neat so i'll throw a little twist on this`
so you don't need to accept this PR, I just like your twitter/blog and thought I'd throw this up

### CODE REVIEW

**Comment by AtomicMaya** [comment]
Hi there, 

Although your idea is good, and will be implemented in a commit with proper credit, the actual code you pushed has a few issues:
- You use `a_url` and that doesn't exist ;
- The fanging and defanging both do the same thing ;
- You create an array of replaced strings that aren't working on the same object.

**Comment by MylesBock** [comment]
Hi,

It's cool that you did actually test something that I didn't (I just wrote a list comprehension in `python3 -i` and copypasted into the GH editor 😅 ), but could you refrain from closing others' PRs?

Please understand that [replace()](https://docs.python.org/3/library/stdtypes.html#str.replace) returns a new object, so in essence I was doing the same thing, just within a list comprehension.
To update the functionality to actually fang/defang properly it merely required swapping key and value in the comprehension.

**Comment by AtomicMaya** [comment]
Hey there, 

I do get that closing PR's is not the best practice, but in this instance it would've required you to modify your code substantially from a source commit that was a few implementations behind `main`.

I am well aware that `replace()` returns a new object (I meant that you weren't necessarily iterating understandably). However, would you agree that the way in which you did that wouldn't necessarily be PEP8 compliant or understandable to everyone, especially considering this is an open-sourced tool ?

I did give you proper credit in 4ed3f8b6be776ba7c1feebaf7ec59f12ed505267 for coming up with it, because I said I would.

Cheers

**Comment by MylesBock** [comment]
I would have approached it more in this manner:

1. I would have made the comments outlining the issues
2. I would have maybe added commits to redress the issues, including slight reformatting to make this PEP8 compliant, or allowed the committer to remediate the issues with the PR

Thanks for the credit, thanks for the response.

**Pull request closed without merging**
